version: '3'

services:
  pgdb:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogapp          
    ports:
      - "5432:5432"
    volumes:
     - "./postgres-data:/var/lib/postgresql/data:rw"

  admin:
    image: adminer
    ports:
      - 8181:8080
